### ISSUE TITLE
'beforeAppChildFn' This method is not implemented

### ISSUE THREAD

**Issue by z-bucket** [tec8297729/jh_debug#2]
I think we should implement this method before implementing the runApp internally. Here is my code:
return runZonedGuarded(
 () async {
    WidgetsFlutterBinding.ensureInitialized();
    if (beforeAppChildFn ! = null) beforeAppChildFn();
    runApp(appChild);
  },
  ...
);

**Comment by tec8297729** [comment]
谢谢你的建议！这块会在后续一版本调整一起完善beforeAppChildFn这方法！！

**Comment by tec8297729** [comment]
@zjl5611882 更新至2.0.1版本，添加了此方法钩子功能
